# Database configuration
database:
  host: localhost
  port: 3306
  user: root
  password: "rootpassword"
  database: ""
  use_pure: false #Uses the pure Python implementation (MySQLConnection)
  auth_plugin: mysql_native_password  # MySQL authentication plugin to use
  ssl: false  # Whether to use SSL for the database connection
  ssl_ca: null  # Path to CA certificate file
  ssl_cert: null  # Path to client certificate file
  ssl_key: null  # Path to client key file
  ssl_verify_cert: false  # Whether to verify server certificate
  ssl_verify_identity: false  # Whether to verify server identity

# Export configuration
export:
  output_dir: exports
  batch_size: 1000
  compression: false
  parallel_workers: $MAX_CPU_THREADS/2  # Use half of available CPU threads
  tables: []  # Empty list means all tables
  where: ""  # Empty string means no WHERE clause
  exclude_schema: false
  exclude_indexes: false
  exclude_constraints: false

# Import configuration
import:
  input_dir: exports  # Same as export.output_dir by default
  batch_size: 1000
  compression: false
  parallel_workers: $MAX_CPU_THREADS/2  # Use half of available CPU threads
  mode: skip  # Options: skip, overwrite, merge, cancel
  database: ""
  exclude_schema: false
  exclude_indexes: false
  exclude_constraints: false
  disable_foreign_keys: false
  continue_on_error: false

# Logging configuration
logging:
  # Verbosity level: DEBUG, INFO, WARNING, ERROR, CRITICAL
  level: INFO
  # Log file path (leave empty for console output only)
  file: ""
  # Log format (default is standard logging format)
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s" 